import '../globals.css';
import Image from 'next/image';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div
          className="signUp-mo-logo-container"
        >
          <Image src="/image/Mo-logo.png"
            className="signUp-mo-logo"
            width={128} height={59}
            alt="MO Logo" />
        </div>
        {children}
      </body>
    </html>
  )
}
