import '../globals.css';
import Image from 'next/image';

export const metadata = {
  title: 'MO',
  description: 'Generated by HCL',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div
          className="signUp-mo-logo-container"
        >
           <Image src="/image/Mo-logo.png"
           priority={true}
            className="signUp-mo-logo"
            width={128} height={59}
            alt="MO Logo" /> 
        </div>
        {children}
      </body>
    </html>
  )
}
