import '../globals.css';
import Image from 'next/image';
import Header from '../src/components/complex/Header/Header';
import SideMenu from '../src/components/complex/Menu/SideMenu';
import SidePanel from '../src/components/complex/Menu/SidePanel';
import { Div } from '../src/components/atomic/MoMolecules/Molecules';
import '../src/styles/Pages/createNewProject/createNewProject.scss';

export const metadata = {
  title: 'MO',
  description: 'Generated by HCL',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <>
        <Header></Header>
        <Div className="create-new-project-main-page">
        <SidePanel></SidePanel>
        {children}
        </Div>
        </>
        
     
  )
}
